[package]
name = "backend"
version.workspace = true
edition.workspace = true

# use only for unit test
[dev-dependencies.wasmer]
version = "4.3"
default-features = false
features = ["std", "cranelift"]
