cargo-features = ["per-package-target"]

[package]
name = "playground_compiler"
edition.workspace = true
version.workspace = true
forced-target = "wasm32-unknown-unknown"

[lib]
crate-type = ["cdylib"]

[dependencies]
backend = { path = "../backend" }
